"""
Demo product catalog — used when DEMO_MODE=true or Airtable is not configured.
Rich enough to showcase all chatbot capabilities: filtering, search, recommendations.
"""

DEMO_PRODUCTS = [
    # ── Footwear ────────────────────────────────────────────────────────────
    {
        "id": "P001",
        "name": "AeroStride Running Shoes",
        "description": "Lightweight mesh runners with responsive foam midsole. Perfect for daily training and long-distance runs. Ultra-breathable upper keeps feet cool.",
        "price": 4499,
        "category": "Footwear",
        "subcategory": "Running",
        "color": "Black/White",
        "rating": 4.7,
        "stock": 23,
        "tags": ["running", "lightweight", "breathable", "training"],
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
    },
    {
        "id": "P002",
        "name": "CloudWalk Comfort Sneakers",
        "description": "Memory foam insole with cushioned outsole designed for all-day comfort. Ideal for walking, travel, and casual everyday wear. Wide toe box for natural foot shape.",
        "price": 3299,
        "category": "Footwear",
        "subcategory": "Casual",
        "color": "White",
        "rating": 4.5,
        "stock": 45,
        "tags": ["walking", "comfort", "casual", "everyday", "travel"],
        "image_url": "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400",
    },
    {
        "id": "P003",
        "name": "Summit Pro Hiking Boots",
        "description": "Waterproof Gore-Tex boots with aggressive lug sole for superior trail grip. Ankle support and Vibram outsole. Built for serious mountain trekking.",
        "price": 7999,
        "category": "Footwear",
        "subcategory": "Hiking",
        "color": "Brown/Tan",
        "rating": 4.8,
        "stock": 12,
        "tags": ["hiking", "waterproof", "trail", "trekking", "outdoor"],
        "image_url": "https://images.unsplash.com/photo-1520219306100-ec4afeeefe58?w=400",
    },
    {
        "id": "P004",
        "name": "UrbanEdge Leather Sneakers",
        "description": "Premium full-grain leather upper with minimalist design. Versatile enough for office to weekend. Rubber cupsole with herringbone pattern.",
        "price": 5499,
        "category": "Footwear",
        "subcategory": "Casual",
        "color": "White/Cream",
        "rating": 4.4,
        "stock": 31,
        "tags": ["leather", "minimalist", "premium", "office", "style"],
        "image_url": "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400",
    },
    {
        "id": "P005",
        "name": "FlexRun Pro Trail Shoes",
        "description": "Zero-drop trail runners with puncture-resistant rock plate. Excellent for rough terrain and ultra-distances. Drainage ports for water crossings.",
        "price": 6299,
        "category": "Footwear",
        "subcategory": "Trail Running",
        "color": "Orange/Grey",
        "rating": 4.6,
        "stock": 8,
        "tags": ["trail", "running", "zero-drop", "ultra", "outdoor"],
        "image_url": "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400",
    },

    # ── Apparel ─────────────────────────────────────────────────────────────
    {
        "id": "P006",
        "name": "TechFit Performance Tee",
        "description": "Moisture-wicking polyester blend with flatlock seams to prevent chafing. UPF 40+ sun protection. Quick-dry fabric for intense workouts.",
        "price": 1299,
        "category": "Apparel",
        "subcategory": "Tops",
        "color": "Black",
        "rating": 4.3,
        "stock": 78,
        "tags": ["workout", "moisture-wicking", "running", "gym", "performance"],
        "image_url": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
    },
    {
        "id": "P007",
        "name": "Alpine Fleece Jacket",
        "description": "300-weight Polartec fleece with wind-resistant outer shell. Zip chest pocket and adjustable hem. Perfect mid-layer for cold-weather activities.",
        "price": 4999,
        "category": "Apparel",
        "subcategory": "Outerwear",
        "color": "Navy Blue",
        "rating": 4.6,
        "stock": 19,
        "tags": ["fleece", "winter", "hiking", "outdoor", "warm"],
        "image_url": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400",
    },
    {
        "id": "P008",
        "name": "Stride Compression Shorts",
        "description": "4-way stretch compression shorts with targeted muscle support. Flat waistband with inner key pocket. Ideal for running, gym, and cycling.",
        "price": 1799,
        "category": "Apparel",
        "subcategory": "Bottoms",
        "color": "Charcoal",
        "rating": 4.4,
        "stock": 55,
        "tags": ["compression", "running", "gym", "cycling", "performance"],
        "image_url": "https://images.unsplash.com/photo-1539185441755-769473a23570?w=400",
    },

    # ── Accessories ─────────────────────────────────────────────────────────
    {
        "id": "P009",
        "name": "ProTrack Sports Watch",
        "description": "GPS-enabled sports watch with heart rate monitor, sleep tracking, and 14-day battery life. Water-resistant to 50m. Compatible with iOS and Android.",
        "price": 12999,
        "category": "Accessories",
        "subcategory": "Wearables",
        "color": "Black",
        "rating": 4.8,
        "stock": 6,
        "tags": ["GPS", "heart rate", "smartwatch", "fitness tracker", "running"],
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
    },
    {
        "id": "P010",
        "name": "HydroMax Running Vest",
        "description": "2.5L hydration vest with 12 pockets including a 1.5L reservoir. Bounce-free fit system with adjustable sternum straps. Perfect for trail runs and hikes.",
        "price": 3799,
        "category": "Accessories",
        "subcategory": "Hydration",
        "color": "Green/Black",
        "rating": 4.5,
        "stock": 14,
        "tags": ["hydration", "trail", "running", "vest", "outdoor"],
        "image_url": "https://images.unsplash.com/photo-1556906781-9a412961a28b?w=400",
    },
    {
        "id": "P011",
        "name": "EliteGrip Gym Gloves",
        "description": "Leather palm grip with wrist wrap support. Perforated back panel for breathability. Silicone grip dots for barbell and dumbbell training.",
        "price": 899,
        "category": "Accessories",
        "subcategory": "Gym",
        "color": "Black",
        "rating": 4.2,
        "stock": 88,
        "tags": ["gym", "weightlifting", "grip", "training", "gloves"],
        "image_url": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    },
    {
        "id": "P012",
        "name": "Recovery Foam Roller",
        "description": "High-density EVA foam roller with textured surface for deep tissue massage. 33cm x 14cm. Essential for post-workout muscle recovery and myofascial release.",
        "price": 1599,
        "category": "Accessories",
        "subcategory": "Recovery",
        "color": "Black/Grey",
        "rating": 4.6,
        "stock": 34,
        "tags": ["recovery", "foam roller", "massage", "muscle", "physio"],
        "image_url": "https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?w=400",
    },
]

DEMO_FAQS = [
    {
        "id": "F001",
        "question": "What is your return policy?",
        "answer": "We offer a 30-day hassle-free return policy. Items must be in original condition with tags attached. Return shipping is free for defective items; a small fee applies for change-of-mind returns. Refunds are processed within 5-7 business days.",
        "category": "Returns",
    },
    {
        "id": "F002",
        "question": "How long does shipping take?",
        "answer": "Standard shipping takes 3-5 business days. Express shipping (1-2 days) is available for an additional fee. Same-day delivery is available in select cities. International orders take 7-14 business days.",
        "category": "Shipping",
    },
    {
        "id": "F003",
        "question": "Do you offer size exchanges?",
        "answer": "Yes! Size exchanges are free within 30 days of purchase. Simply initiate an exchange through your order history page and drop off the item at any courier pickup point. The replacement will be shipped within 2 business days of receiving your return.",
        "category": "Returns",
    },
    {
        "id": "F004",
        "question": "Are your products authentic?",
        "answer": "All products are 100% authentic and sourced directly from brand manufacturers or authorized distributors. Every item comes with a certificate of authenticity and brand warranty.",
        "category": "Product",
    },
    {
        "id": "F005",
        "question": "How do I track my order?",
        "answer": "Once your order ships, you'll receive a tracking number via email and SMS. You can also track orders in real-time through your account dashboard under 'My Orders'. We partner with major courier services including TCS, Leopards, and DHL.",
        "category": "Orders",
    },
    {
        "id": "F006",
        "question": "What payment methods do you accept?",
        "answer": "We accept credit/debit cards (Visa, Mastercard, Amex), bank transfers, JazzCash, EasyPaisa, and Cash on Delivery (COD) for eligible orders. All online payments are secured with 256-bit SSL encryption.",
        "category": "Payment",
    },
    {
        "id": "F007",
        "question": "How do I find the right shoe size?",
        "answer": "Use our Size Guide on each product page — measure your foot length in cm and match it to the size chart. For running shoes, we recommend going half a size up for optimal comfort during swelling after long runs. Still unsure? Chat with us and we'll help!",
        "category": "Product",
    },
    {
        "id": "F008",
        "question": "Can I cancel my order?",
        "answer": "Orders can be cancelled within 2 hours of placement free of charge. After that, you may need to wait for delivery and initiate a return. Contact our support team immediately via chat for cancellation requests.",
        "category": "Orders",
    },
]

DEMO_POLICIES = [
    {
        "id": "POL001",
        "title": "Return & Refund Policy",
        "content": "30-day returns accepted for all items in original condition. Free returns for defective products. Refunds to original payment method within 5-7 business days. Exchange available for size/color with free shipping.",
        "category": "Policy",
    },
    {
        "id": "POL002",
        "title": "Shipping Policy",
        "content": "Free standard shipping on orders above Rs. 3,000. Express 24-hour delivery available. We ship nationwide across Pakistan with tracking on all orders. International shipping available to GCC countries.",
        "category": "Policy",
    },
    {
        "id": "POL003",
        "title": "Warranty Policy",
        "content": "All footwear carries a 6-month manufacturing defect warranty. Electronics and wearables have a 1-year warranty. Warranty claims must be initiated within the warranty period with proof of purchase.",
        "category": "Policy",
    },
    {
        "id": "POL004",
        "title": "Privacy Policy",
        "content": "We collect only necessary data to process your orders. Your personal information is never sold to third parties. We use industry-standard encryption for all transactions. You can request data deletion at any time.",
        "category": "Policy",
    },
]

DEMO_ORDERS = {
    "ORD-2024-001": {
        "id": "ORD-2024-001",
        "status": "Delivered",
        "items": ["AeroStride Running Shoes (Size 42)", "TechFit Performance Tee (L)"],
        "total": 5798,
        "placed_at": "2024-12-10",
        "delivered_at": "2024-12-14",
        "tracking": "TCS-789456123",
    },
    "ORD-2024-002": {
        "id": "ORD-2024-002",
        "status": "In Transit",
        "items": ["Summit Pro Hiking Boots (Size 43)"],
        "total": 7999,
        "placed_at": "2024-12-20",
        "delivered_at": None,
        "estimated_delivery": "2024-12-24",
        "tracking": "LEOP-456789012",
    },
    "ORD-2024-003": {
        "id": "ORD-2024-003",
        "status": "Processing",
        "items": ["ProTrack Sports Watch", "HydroMax Running Vest"],
        "total": 16798,
        "placed_at": "2024-12-22",
        "delivered_at": None,
        "estimated_delivery": "2024-12-27",
        "tracking": None,
    },
}
